connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres:5432/pulso
iceberg.jdbc-catalog.connection-user=pulso
iceberg.jdbc-catalog.connection-password=pulso
iceberg.jdbc-catalog.catalog-name=pulso_lake
hive.metastore.warehouse.dir=s3://pulso-lakehouse/
hive.s3.endpoint=http://minio:9000
hive.s3.path-style-access=true
hive.s3.aws-access-key=minioadmin
hive.s3.aws-secret-key=minioadmin
